name: "Zip it"
description: "zip all the files needs to run the script in a zip file ready to rumble"
inputs:
  pkg_directories:
    description: "directories to be zipped"
    required: true
  bin:
    description: "files that go in the bin directory"
    required: false
  lib:
    description: "files that go in the lib directory"
    required: false
  share:
    description: "files that go in the share directory"
    require: false
runs:
  using: 'docker'
  image: 'Dockerfile'
