name: "Zip it"
description: "zip all the files needs to run the script in a zip file ready to rumble"
env:
  OWNER: ${{ github.repository_owner }}
  PACKAGE_NAME: ${{ github.event.repository.name }}
inputs:
  prefix:
    description: "the prefix into which it will be installed"
    required: true
  maintainer:
    description: "the user/organization under who the package will be released"
    required: true
  pkg_directories:
    description: "directories to be zipped"
    required: true
  package_name:
    description: "name of the zip"
    required: true
  bin:
    description: "files that go in the bin directory"
    required: false
  lib:
    description: "files that go in the lib directory"
    required: false
  share:
    description: "files that go in the share directory"
    require: false
  data_directory:
    description: "files that go in the share/<package_name> directory"
    require: false
runs:
  using: 'docker'
  image: 'Dockerfile'
