name: "Zip it"
description: "zip all the files needs to run the script in a zip file ready to rumble"
inputs:
  prefix:
    description: "the prefix into which it will be installed"
    required: true
    default: ${HOME}/.local
  owner:
    description: "the user/organization under who the package will be released"
    required: true
    default: ${{ github.repository_owner }}
  repo_name:
    description: "name of the repository"
    required: true
    default: ${{ github.event.repository.name }}
  pkgrel:
    description: "the release version"
    required: true
    default: ${{ github.ref_name }}
  pkg_directories:
    description: "directories to be zipped"
    required: true
  package_name:
    description: "name of the zip"
    required: true
    default: ${{ github.event.repository.name }}
  bin:
    description: "files that go in the bin directory"
    required: false
  lib:
    description: "files that go in the lib directory"
    required: false
  share:
    description: "files that go in the share directory"
    require: false
  data_directory:
    description: "files that go in the share/<package_name> directory"
    require: false
  config:
    description: "config files for the package"
    require: false
runs:
  using: 'docker'
  image: 'Dockerfile'
