#!/bin/bash
SCRP_DIR=$(dirname "${BASH_SOURCE[0]}")
source $SCRP_DIR/crackle.conf

download_%package%(){
	echo "downloading latest version"
	wget -q https://github.com/${maintainer}/${name}/releases/latest/download/${name}.zip -O $HOME/Downloads/${name}.zip
}

unzip_%package%() {
	echo "unpacking..."
	unzip -q $HOME/Downloads/${name}.zip -d $HOME/${name}
}

install_%package%(){
	mkdir -p ${prefix}/bin
	mkdir -p ${prefix}/lib
	mkdir -p ${comprefix}
	chmod 755 ${SCRP_DIR}/bin/*
	cp -f $SCRP_DIR/bin/* ${prefix}/bin
        [[ -d $SCRP_DIR/lib ]] && cp -f $SCRP_DIR/lib/* ${prefix}/lib
        [[ -d $SCRP_DIR/share ]] && cp -rf $SCRP_DIR/share/* ${prefix}/share
}

if [ "$1" = "setup" ]; then
	install_%package%;
	rm -r $HOME/${name};
	rm -r $HOME/Downloads/${name}.zip;
fi
